### ISSUE TITLE
Background Image is jumping on iOS

### ISSUE THREAD

**Issue by club5000** [club5000/club5000.github.io#1]
I guess this has something to do with the _Status Bar_. It seems like the image background size will be recalculated by _backstretch_ as soon as the _Status Bar_ leaves the screen.

# Loading Page (with Status Bar)
![img_3411](https://user-images.githubusercontent.com/31864790/30559595-71f66970-9cb5-11e7-8da5-9e34bb12ab99.PNG)

# Scrolling down (Status Bar gets smaller and white bar appears)
![img_3409](https://user-images.githubusercontent.com/31864790/30559596-71f7e854-9cb5-11e7-99db-c0c4d346de62.PNG)

# Stop scrolling (Image size was recalculated and white bar disappears)
![img_3410](https://user-images.githubusercontent.com/31864790/30559597-71fbaf3e-9cb5-11e7-9e12-cf7e97f6429c.PNG)

[I already tried to hack this by scrolling 1 px down ](https://github.com/club5000/club5000.github.io/blob/master/assets/javascripts/application.js#L10)but this does not work on newer iOS versions anymore.

**Comment by JanOwiesniak** [comment]
I'm using [backstretch](https://github.com/jquery-backstretch/jquery-backstretch) because i had several issues with fullsize background images on mobile devices. I'm totally happy with a solution that does not depend on backstretch and uses plain CSS to solve this problem.

**Comment by club5000** [comment]
Fixed by removing backstretch.
