### ISSUE TITLE
Reduce usage of CSS !important rule

### ISSUE THREAD

**Issue by club5000** [club5000/club5000.github.io#19]
Since i use `materialize` (navbar and buttons) i had to introduce a lot of `!important` rules to overwrite the `materialize` default styles (e.g. `h1` and `h2`).

This feels wrong to me -> Get rid of as much as `!important` rules as possible.

**Comment by JanOwiesniak** [comment]
Get rid of `materialize` and implement Call-To-Action Button and Navigation on my own

**Comment by JanOwiesniak** [comment]
Done.
